linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  presets:
    - bugs
    - comment
    - complexity
    - error
  #  - format
    - import
  #  - metalinter
  #  - module
    - performance
  #  - style
  #  - test
    - unused
linters-settings:
  cyclop:
    max-complexity: 12
  depguard:
    rules:
      main:
        files:
          - $all
        allow:
          - $gostd
          - github.com/go-ble/ble
          - github.com/stefanjenkner/fdf-console-monitor
  funlen:
    ignore-comments: true
