linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  presets:
    - bugs
    - comment
  #  - complexity
  #  - error
  #  - format
  #  - import
  #  - metalinter
  #  - module
    - performance
  #  - style
  #  - test
    - unused